// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl4BNqnGMwRpn1qC8rYDXCFSZSDURm9vU',
    appId: '1:936338121467:web:16ade176d53962f1a4065e',
    messagingSenderId: '936338121467',
    projectId: 'tasker-asher-app',
    authDomain: 'tasker-asher-app.firebaseapp.com',
    storageBucket: 'tasker-asher-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6B9Q0GyYp1xlSNlq5S6RoMzzn8AJMOg',
    appId: '1:936338121467:android:54eb4c685cf6cf66a4065e',
    messagingSenderId: '936338121467',
    projectId: 'tasker-asher-app',
    storageBucket: 'tasker-asher-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCydICzgijAgFj8FjloEVnZHug_DO7d2CY',
    appId: '1:936338121467:ios:2c1888e427b2940ca4065e',
    messagingSenderId: '936338121467',
    projectId: 'tasker-asher-app',
    storageBucket: 'tasker-asher-app.appspot.com',
    androidClientId: '936338121467-i6p25srb9oapgdcv56d8nclsmlnca7aq.apps.googleusercontent.com',
    iosClientId: '936338121467-aqa4lkvd0homte5sb7u0gmc8dprtls52.apps.googleusercontent.com',
    iosBundleId: 'app.tasker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCydICzgijAgFj8FjloEVnZHug_DO7d2CY',
    appId: '1:936338121467:ios:2c1888e427b2940ca4065e',
    messagingSenderId: '936338121467',
    projectId: 'tasker-asher-app',
    storageBucket: 'tasker-asher-app.appspot.com',
    androidClientId: '936338121467-i6p25srb9oapgdcv56d8nclsmlnca7aq.apps.googleusercontent.com',
    iosClientId: '936338121467-aqa4lkvd0homte5sb7u0gmc8dprtls52.apps.googleusercontent.com',
    iosBundleId: 'app.tasker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl4BNqnGMwRpn1qC8rYDXCFSZSDURm9vU',
    appId: '1:936338121467:web:085c6e96114cf167a4065e',
    messagingSenderId: '936338121467',
    projectId: 'tasker-asher-app',
    authDomain: 'tasker-asher-app.firebaseapp.com',
    storageBucket: 'tasker-asher-app.appspot.com',
  );
}
